// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC73r9e0-fSJQKx4bSDBwr8N2ZsAkeUVVE',
    appId: '1:497677158762:web:8dcb664fcd9ee1c71ebd13',
    messagingSenderId: '497677158762',
    projectId: 'todoappfirebase-7732e',
    authDomain: 'todoappfirebase-7732e.firebaseapp.com',
    storageBucket: 'todoappfirebase-7732e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALKcT0lgtwyb1qJRoyFI0f9s8CJMdzUNA',
    appId: '1:497677158762:android:20ba75fa05b7726b1ebd13',
    messagingSenderId: '497677158762',
    projectId: 'todoappfirebase-7732e',
    storageBucket: 'todoappfirebase-7732e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfBUZO1zePtUxLl1N4Dik25oLX3Vxa-Rs',
    appId: '1:497677158762:ios:0799f26b6456af921ebd13',
    messagingSenderId: '497677158762',
    projectId: 'todoappfirebase-7732e',
    storageBucket: 'todoappfirebase-7732e.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfBUZO1zePtUxLl1N4Dik25oLX3Vxa-Rs',
    appId: '1:497677158762:ios:0799f26b6456af921ebd13',
    messagingSenderId: '497677158762',
    projectId: 'todoappfirebase-7732e',
    storageBucket: 'todoappfirebase-7732e.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC73r9e0-fSJQKx4bSDBwr8N2ZsAkeUVVE',
    appId: '1:497677158762:web:6e1e14b4dc02c21b1ebd13',
    messagingSenderId: '497677158762',
    projectId: 'todoappfirebase-7732e',
    authDomain: 'todoappfirebase-7732e.firebaseapp.com',
    storageBucket: 'todoappfirebase-7732e.firebasestorage.app',
  );
}
